import FormTypes from "../FormTypes";

const dataArray: Array<FormTypes> = [
    {ID: 0, Type: 'PageBreak', Title: 'Syfte'},
    {ID: 1, Type: 'Description', Header: 'Syfte med AI-systemet och ansvarsfördelning', Description: "", TopHeading: true}, 
    {ID: 2, Type: 'Text', Value: '', Header: 'Hur ska AI-systemet användas?'},
    {ID: 3, Type: 'Text', Value: '', Header: 'Vilka personer kommer påverkas av AI-lösningen?'},
    {ID: 4, Type: 'Text', Value: '', Header: 'Vilka mål ska användningen av AI uppnå, t.ex. vilka problem ska AI lösa?'},
    {ID: 5, Type: 'TextChoice', Value: '', Header: 'Finns det en person med utpekat ansvar för AI-systemet?', Choice: 'NA', NoText: 'Denna text dyker upp om man väljer Nej.' , YesText: 'Kan den utpekade personen utöva tillsyn över systemet (se även 3. Systemkrav) *enligt förslaget till AI-förordning art 14 ska AI-system med hög risk utformas och utvecklas, inbegripet med lämpliga verktyg för användargränssnitt mellan människa och maskin, att fysiska personer på ett effektivt sätt kan ha tillsyn över dem när de används* ?'},
    {ID: 6, Type: 'Text', Value: '', Header: 'Kommer AI-systemet användas för att ge stöd till ett förvaltningsbeslut?'},
    {ID: 7, Type: 'TextChoice', Value: '', Header: 'Kommer AI-systemet användas för att fatta ett automatiserat beslut?', Choice: 'NA', YesText: 'Det finns flera krav när det gäller automatiserade beslut enligt GDPR som Integritetsskyddsmyndigheten redogör för <a href="https://www.imy.se/privatperson/dataskydd/dina-rattigheter/automatiserade-beslut/">Dina rättigheter när beslut fattas automatiskt | IMY</a> – har ni följt detta?'},
    {ID: 8, Type: 'TextChoice', Value: '', Header: 'Kommer privatpersoner och företag att veta att AI används?', Choice: 'NA', YesText: 'Beskriv hur.'}, /* Om nej motivera */
    {ID: 9, Type: 'TextChoice', Value: '', Header: 'Kommer privatpersoner och företag få information om hur lösningen är utvecklad?', Choice: 'NA', YesText: 'Beskriv hur.'}, /* Om nej motivera */
    {ID: 10, Type: 'Text', Value: '', Header: 'Hur ska AI-lösningen förvaltas, övervakas och utvärderas efter implementering?'},   
    
    /* Ny sida */
    {ID: 11, Type: 'PageBreak', Title: 'Värdegrund'},
    {ID: 12, Type: 'Description', Header: 'Värdegrund och juridik', Description: "", TopHeading: true},
    {ID: 13, Type: 'TextArea', Value: '', Header: 'Redovisa en analys av vilka personer som ska utveckla, träna och utvärdera AI-lösningen utifrån diskriminersgrunderna i diskrimineringslagen?'},
    {ID: 14, Type: 'TextChoice', Value: '', Header: 'Finns det kända privilegierade eller underprivilegierade grupper inom verksamhetsområdet där AI ska användas?', Choice: 'NA', YesText: 'Vilka grupper är det och har ni gjort en analys om detta kan påverka AI-systemets resultat?'},  
    {ID: 15, Type: 'TextArea', Value: '', Header: 'Hur säkerställer ni att data som ska användas för att träna lösningen är representativt och hur kompenserar ni för eventuell bias? <a href="https://www.regeringen.se/regeringens-politik/globala-malen-och-agenda-2030/agenda-2030-mal-5-jamstalldhet/">Agenda 2030 | Mål 5 | Jämställdhet - Regeringen.se</a>'},   
    {ID: 16, Type: 'TextArea', Value: '', Header: 'Vilka processer har ni för att veta om lösningen behöver tränas om pga. t.ex. omvärldshändelser?'},   
    {ID: 17, Type: 'TextArea', Value: '', Header: 'Hur skulle AI-lösningen kunna påverka utfallen för de jämställdhetspolitiska målen? *ext link*'},   /* Add link */
    {ID: 18, Type: 'Text', Value: '', Header: 'Vilka risker finns det för att AI-lösningen uppfattas som integritetskränkande?'},   
    {ID: 19, Type: 'TextChoice', Value: '', Header: 'Kan AI-lösningen komma att användas för andra ändamål än det avsedda?', Choice: 'NA', YesText: 'Tänk på att förtroendemodellen behöver användas vid varje tillämpning'},   
    {ID: 20, Type: 'Text', Value: '', Header: 'Hur mäter ni att AI-lösningen är tillräckligt tränad?'},  
    {ID: 21, Type: 'TextChoice', Value: '', Header: 'Behandlar ni personuppgifter i ert AI-system? ', Choice: 'NA', YesText: `<ul><li>Beskriv vilka personuppgifter och den rättsliga grunden för behandlingen.</li><li>Har avvägning mellan kraven i den allmänna dataskyddsförordningen på uppgiftsminimering och lagringsminimering i förhållande till kravet på korrekthet? Beskriv i så fall er slutsats </li></ul>`}, 
    {ID: 22, Type: 'TextChoice', Value: '', Header: 'Har ni gjort en informationsklassning?', Choice: 'NA', YesText: 'Vad har den för diarienummer?'},   
    {ID: 23, Type: 'TextChoice', Value: '', Header: 'Har ni gjort en hot-och riskanalys?', Choice: 'NA', YesText: 'Vad har den för diarienummer?'},   
    {ID: 24, Type: 'TextChoice', Value: '', Header: 'Har ni gjort andra analyser t.ex. med anledning av bestämmelser för krisberedskap eller enligt säkerhetsskyddslagen? ', Choice: 'NA', YesText: 'Uppge diarienummer *som i alla fall av utlämnande av allmän handling gäller att myndigheten gör en sekretessprövning*'},     
    
    /* Ny sida */
    {ID: 25, Type: 'PageBreak', Title: 'Design'},
    {ID: 26, Type: 'Description', Header: 'Design, realiseringsprocess, systemkrav', Description: "", TopHeading: true},
    {ID: 27, Type: 'TextArea', Value: '', Header: 'Beskriv målprocesserna för AI-komponeneter i systemet'},
    {ID: 28, Type: 'TextChoice', Value: '', Header: 'Är era AI-komponenter delar i ett större IT-system?', Choice: 'NA', YesText: 'Beskriv systemets start-arkitektur, AI-komponenters målprocess och AI-komponenternas roll.'},
    {ID: 29, Type: 'Text', Value: '', Header: 'Har ni gjort en analys av hur mycket energi AI-systemet kräver? Räkna CO2 (enligt UNESCO bör vara organisation tänka på hållbart)'},
    {ID: 30, Type: 'TextChoice', Value: '', Header: 'Finns det andra komponenter( ex regler) inbyggda i systemet som interagerar med AI-komponenternas utfall och påverkar systemets funktionalitet?', Choice: 'NA', YesText: 'Beskriv hur AI-komponenterna och de andra funktionerna interagerar tillsammans och påverkar funktion.'},
    {ID: 31, Type: 'TextArea', Value: '', Header: 'Klarlägg de krav som finns för att utveckla AI-lösningen. (inklusive krav  för monitorering och uppföljning av enskilda AI-komponenter och hela systemet.)'},
    {ID: 32, Type: 'TextArea', Value: '', Header: 'Dokumentera hur ni tolkar de krav som är otydliga.'},
    {ID: 33, Type: 'TextArea', Value: '', Header: 'Klarlägg och dokumentera andra krav som ställs för planering, dokumentation, mätningar, test, verifiering och spårbarhet för utveckling och drift.'},
    {ID: 34, Type: 'Description', Header: 'Analys av tillgängligt data gentemot kriterier i Steg 2.', Description: ""},
    {ID: 35, Type: 'TextArea', Value: '', Header: 'Är det rättsligt klarlagt hur vi kan använda data?'},
    {ID: 36, Type: 'TextArea', Value: '', Header: 'Hur kommuniceras till användare att vi samlat data som används i utveckling av AI-tjänster? Hur transparant är vi om användning av uppgifter?'},
    {ID: 37, Type: 'TextArea', Value: '', Header: 'Kommer insamlat data delas med 3:e part? Motivera ställningstagande.'},
    {ID: 38, Type: 'Text', Value: '', Header: 'Tillgänglighet till relevant data?'}, 
    {ID: 39, Type: 'TextArea', Value: '', Header: 'Beskriv hur data kommer att lagras, hållas spårbart mot källa, samt skyddas.'},
    {ID: 40, Type: 'TextChoice', Value: '', Header: 'Finns krav på att data ska gallras? ', Choice: 'NA', YesText: 'Beskriv hur detta hanteras och eventuell påverkan på arbetet.'},
    {ID: 41, Type: 'TextChoice', Value: '', Header: 'Kommer data att innehålla känsliga uppgifter?', Choice: 'NA', YesText: 'Hur kommer dessa uppgifter att hanteras och skyddas?'},
    {ID: 42, Type: 'Description', Header: 'Analys: Datakvalitet och komplexitet i förhållande till kriterier enligt Steg 2? Fakta om dataset.', Description: ""}, 
    {ID: 43, Type: 'TextChoice', Value: '', Header: 'Är datakvaliteten sådan att data behöver bearbetas?', Choice: 'NA', YesText: 'Beskriv hur data hanteras/bearbetas för att förbättra datakvaliteten?'},
    {ID: 44, Type: 'TextChoice', Value: '', Header: 'Finns det risk att data innehåller insamlingsbias?', Choice: 'NA', YesText: 'Beskriv hur denna risk hanteras och hur eventuell bias reduceras.'},
    {ID: 45, Type: 'TextChoice', Value: '', Header: 'Finns andra potentiella källor till bias i datat?', Choice: 'NA', YesText: 'Beskriv hur bias-källorna hanteras.'},
    {ID: 46, Type: 'Description', Header: 'Dokumentera och redovisa resultaten från momenten ovan. Håll god ordning och spårbarhet.', Description: ""},
    {ID: 47, Type: 'TextArea', Value: '', Header: 'Om andra eller kvarstående problem finns med datat? Finns en plan för att ta hand om dessa problem.'}, 
    {ID: 48, Type: 'Text', Value: '', Header: 'Är data tillräckligt bra för att gå vidare?  Beskriv vad som gör att vi inte skulle kunna gå vidare?'}, 
    {ID: 49, Type: 'Description', Header: 'Gör en kvalitetsplan för den tillämpning du har för design/realiseringen/dokumentation av AI-funktionalitet och dess tillhörande infrastruktur.', Description: ""},
    {ID: 50, Type: 'TextArea', Value: '', Header: 'Beskriv hur Design och Realiseringsteamet är sammansatt. (Ex om teamet är tvärfunktionellt( funktioner/kompetenser), om kunder/användare deltar i olika moment et c)'}, 
    {ID: 51, Type: 'TextArea', Value: '', Header: 'Beskriv kort designmetod(systemnivå) för system med AI-komponenter. Beskriv även kort hur initialt planerad interaktion med AI-komponenter ska realiseras.'}, 
    {ID: 52, Type: 'Text', Value: '', Header: 'Beskriv kort realiseringsprocessen för AI-komponenter.'},
    {ID: 53, Type: 'TextChoice', Value: '', Header: 'Behöver tillämpningen vara tolkningsbar och/eller förklaringsbar? ', Choice: 'NA', YesText: 'Hur löses detta?'}, 
    {ID: 54, Type: 'Text', Value: '', Header: 'Uppdateras modellen i tillämpning automatiskt via nytt data? Finns det risker med detta?'},
    {ID: 55, Type: 'TextArea', Value: '', Header: 'Motivera kortfattat för AI-komponenter designval och realisering av datafångst och databearbetningsflöde.'}, 
    {ID: 56, Type: 'TextArea', Value: '', Header: 'Motivera kortfattat för AI-komponenter val och realisering av AI-algoritmer.'},
    {ID: 57, Type: 'TextChoice', Value: '', Header: 'Optimeras AI-modeller efter intial träning/test med exempelvis ”Hypertuning”?', Choice: 'NA', YesText: 'Beskriv kortfattas syfte och effekt.'},
    {ID: 58, Type: 'TextArea', Value: '', Header: 'Utifrån punkterna i kvalitetsplan genomför utvecklingsarbetet. Beskriv eventuella avvikelser avvikelser som uppkommit gentemot inititial plan och deras påverkan mot ex krav m m.'}, 
    {ID: 59, Type: 'Text', Value: '', Header: 'Sätt AI-funktionaliteten i sin infrastruktur för att kunna driftsättas. Uppfylls driftkrav?'},   
    
    /* Ny sida */
    {ID: 60, Type: 'PageBreak', Title: 'Resultat'},  
    {ID: 61, Type: 'Description', Header: 'Resultat, format och lagring', Description: "", TopHeading: true},  
    {ID: 62, Type: 'TextArea', Value: '', Header: 'Hur presterar AI-komponenter separat? (Beskriv med fördel ”confusion”-matris mått, lift-kurvor etc utifrån tillämpning och krav)'}, 
    {ID: 63, Type: 'TextArea', Value: '', Header: 'Hur presterar IT-systemet inklusive AI-komponenterna som helhet? (Beskriv med fördel ”confusion”-matris mått, lift-kurvor etc utifrån tillämpning, krav. Beskriv  så att prestandan blir förståeligt för användare av systemet)'}, 
    {ID: 64, Type: 'TextArea', Value: '', Header: 'Ange tillgängliga referenser till eller beskriv kort metodiken i använda utvärderingsmetoder.'}, 
    {ID: 65, Type: 'TextChoice', Value: '', Header: 'Kan man om man försöker, återupprepa och reproducera design/realisering och få samma resultat?', Choice: 'NA', YesText: 'Beskriv varför inte och hur det kan påverka utfallet?'},
    {ID: 66, Type: 'TextArea', Value: '', Header: 'Finns ett systematiskt sätt att säkra spårbarhet och resultat för AI-komponenter: version,  slutliga förmåga, drift period, utfall under drift, monitorering över tid.<ul><li>Om ja: Beskriv kort hur spårbarheten upprätthålls.</li><li>Om nej: Motivera varför spårbarhet inte behöver upprätthållas.</li></ul>'}, 
    {ID: 67, Type: 'TextChoice', Value: '', Header: 'Finns resultat från Systemtester med användare av systemet? ', Choice: 'NA', YesText: 'Beskriv  vilka tester som genomfördes och resultat.'},
    {ID: 68, Type: 'TextChoice', Value: '', Header: 'Finns liknande AI-system/komponenter i andra IT-system som det går att jämföra prestanda emot? ', Choice: 'NA', YesText: 'Beskriv jämförelsen och referera till källan.'},
    {ID: 69, Type: 'TextArea', Value: '', Header: 'Finns begränsningar i AI-systemet/AI-komponenter som påverkar ställda krav?'},   
    {ID: 70, Type: 'Text', Value: '', Header: 'Modelinformation *vilken version av AI-systemet är detta och var har den utvecklats*'}, 
    {ID: 71, Type: 'TextArea', Value: '', Header: 'Arkitektur *beskriv AI-systemets arkitektur* utifrån de ingående AI-komponenternas syfte och funktionalitet.'}, 
    {ID: 72, Type: 'Text', Value: '', Header: 'Finns det några licenser kopplade till de AI-komponenter som ingår i AI-systemet ?'}, 
    {ID: 73, Type: 'TextArea', Value: '', Header: 'Kan ni förklara lösningens utfall? '}, 
    {ID: 74, Type: 'TextArea', Value: '', Header: 'Vad ska förklaringen användas till?  '},
    {ID: 75, Type: 'TextArea', Value: '', Header: 'Beskriv hur kunder/användare av AI-systemet funktionalitet kan ge feedback, hantera klagomål och felaktigheter.'},
    {ID: 76, Type: 'TextArea', Value: '', Header: 'Finns planering för hur man ska agera då AI-systemet inte fungerar som det ska?'},
  ];

  export default dataArray;