on:
  workflow_dispatch:
    inputs:
      delete_file:
        description: "Delete file"
        required: false
        default: ""

name: Azure - build/push image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: "Docker login"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Print docker version tag
        run: |
          echo "${{ secrets.REGISTRY_LOGIN_SERVER }}/digg-dataportal-v2:${{ steps.package-version.outputs.current-version}}-b.${{ github.run_number }}"

      - name: Print commits url
        run: |
          echo "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

      - name: Print file to remove
        run: |
          echo "File to remove before build: ${{ github.event.inputs.delete_file }}"

      - name: use buildx
        uses: docker/setup-buildx-action@v1

      - name: build_publish_image
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          push: true
          build-args: delete_file=${{ github.event.inputs.delete_file }}
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/digg-dataportal-v2:latest,${{ secrets.REGISTRY_LOGIN_SERVER }}/digg-dataportal-v2:${{ steps.package-version.outputs.current-version}}-b.${{ github.run_number }},${{ secrets.REGISTRY_LOGIN_SERVER }}/digg-dataportal-v2:${{ github.sha }},${{ secrets.REGISTRY_LOGIN_SERVER }}/digg-dataportal-v2:branch-${{ steps.extract_branch.outputs.branch }}
